# Generated by Django 5.1.15 on 2026-04-15 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content_rating', models.CharField(max_length=10)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('duration_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('raw_s3_key', models.CharField(blank=True, max_length=1024)),
                ('multipart_upload_id', models.CharField(blank=True, max_length=255)),
                ('hls_base_path', models.CharField(blank=True, max_length=1024)),
                ('master_playlist', models.CharField(blank=True, max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='videos_vide_status_ffba77_idx'), models.Index(fields=['created_at'], name='videos_vide_created_f7522a_idx')],
            },
        ),
    ]
